
$(document).ready(function(){
  $("#left").mouseover(function(){
    $("#image").attr("src","left.gif");
    $("#image2").attr("src","left.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#right").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","left.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#lefttop").mouseover(function(){
    $("#image").attr("src","lefttop.gif");
    $("#image2").attr("src","lefttop.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#righttop").mouseover(function(){
    $("#image").attr("src","righttop.gif");
    $("#image2").attr("src","lefttop.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#centertop").mouseover(function(){
    $("#image").attr("src","centertop.gif");
    $("#image2").attr("src","lefttop.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#leftbottom").mouseover(function(){
    $("#image").attr("src","leftbottom.gif");
    $("#image2").attr("src","leftbottom.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#rightbottom").mouseover(function(){
    $("#image").attr("src","rightbottom.gif");
    $("#image2").attr("src","leftbottom.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#centerbottom").mouseover(function(){
    $("#image").attr("src","centerbottom.gif");
    $("#image2").attr("src","leftbottom.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#image").mouseover(function(){
    $("#image2").attr("src","left.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#left2").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","left.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#right2").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","right.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#lefttop2").mouseover(function(){
    $("#image").attr("src","righttop.gif");
    $("#image2").attr("src","lefttop.gif");
    $("#image3").attr("src","lefttop.gif");
  });
  $("#righttop2").mouseover(function(){
    $("#image").attr("src","righttop.gif");
    $("#image2").attr("src","righttop.gif");
    $("#image3").attr("src","lefttop.gif");
  });
  $("#centertop2").mouseover(function(){
    $("#image").attr("src","righttop.gif");
    $("#image2").attr("src","centertop.gif");
    $("#image3").attr("src","lefttop.gif");
  });
  $("#leftbottom2").mouseover(function(){
    $("#image").attr("src","rightbottom.gif");
    $("#image2").attr("src","leftbottom.gif");
    $("#image3").attr("src","leftbottom.gif");
  });
  $("#rightbottom2").mouseover(function(){
    $("#image").attr("src","rightbottom.gif");
    $("#image2").attr("src","rightbottom.gif");
    $("#image3").attr("src","leftbottom.gif");
  });
  $("#centerbottom2").mouseover(function(){
    $("#image").attr("src","rightbottom.gif");
    $("#image2").attr("src","centerbottom.gif");
    $("#image3").attr("src","leftbottom.gif");
  });
  $("#image2").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#left3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","right.gif");
    $("#image3").attr("src","left.gif");
  });
  $("#right3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","right.gif");
    $("#image3").attr("src","right.gif");
  });
  $("#lefttop3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","righttop.gif");
    $("#image3").attr("src","lefttop.gif");
  });
  $("#righttop3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","righttop.gif");
    $("#image3").attr("src","righttop.gif");
  });
  $("#centertop3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","righttop.gif");
    $("#image3").attr("src","centertop.gif");
  });
  $("#leftbottom3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","rightbottom.gif");
    $("#image3").attr("src","leftbottom.gif");
  });
  $("#rightbottom3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","rightbottom.gif");
    $("#image3").attr("src","rightbottom.gif");
  });
  $("#centerbottom3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","rightbottom.gif");
    $("#image3").attr("src","centerbottom.gif");
  });
  $("#image3").mouseover(function(){
    $("#image").attr("src","right.gif");
    $("#image2").attr("src","right.gif");
  });
});
